### ISSUE TITLE
userErrors in Payload interface?

### ISSUE THREAD

**Issue by rajington** [Shopify/graphql-design-tutorial#9]
> Obviously would like to start with a huge thank you to the authors of this amazing doc (seems like a recurring preface in all these "issues")

If all mutations should have this `userErrors` field, would it make sense to recommend a `Payload` interface with with that field?

**Comment by rajington** [comment]
> GraphQL does include explicit support for query-level errors, these are not ideal for business-level mutation failures

I'm also curious in what ways `errors` wasn't sufficient, I think more description here would help since it does push complexity to every mutation's handling.

Apollo includes additional information via [`extensions`](https://www.apollographql.com/docs/apollo-server/features/errors#codes), could a pattern there work instead?

I've noticed the "errors as data" pattern in other places, but it was just called `errors`. Was `UserError` decided to be a more descriptive name? allow for other types of error prefixes? to avoid the name collision in various languages? or just to use a different name than the spec?

**Comment by eapache** [comment]
> If all mutations should have this userErrors field, would it make sense to recommend a Payload interface with with that field?

Hmm, we've never considered that because we've never ended up with client code that would be able to make use of it. That said, you're not wrong that it would work.

The other interesting note is that we've been experimenting with making `UserError` itself an interface (instead of a concrete type) in order to provide room for concrete implementations with specific error codes and other error data.

> I'm also curious in what ways errors wasn't sufficient, I think more description here would help since it does push complexity to every mutation's handling.

The spec requires that if a field (or mutation) returns top-level errors, it *not* return any value besides null. It is useful and important for many mutations to be able to return errors and data.

Re. the name, `UserError` was chosen to avoid confusion with the spec's errors, and to be more descriptive. Generally we expect `UserError`s are caused by the user (or the "business logic" end of the client) and top-level errors are more systematic formatting or transport-layer issues.

**Comment by rajington** [comment]
read your comment but forgot to close this, thanks for the info!
